version: "3"


services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: hillel_support
    container_name: hillel_support_api
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - ./:/app/

  broker:
    image: "redis:latest"
    container_name: hillel_support_broker
    ports:
      - "6379:6379" 

  mailing:
    image: mailhog/mailhog:latest
    container_name: hillel_support_mailing
    env_file: ".env"
    ports:
      - "1025:1025"
      - "8025:8025"

  database:
    image: "postgres:16"
    container_name: hillel_support_database
    env_file: ".env"
    ports:
      - "5432:5432" 
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data: {}