# Generated by Django 4.2.11 on 2024-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="massege",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
