# Generated by Django 4.2.11 on 2024-04-16 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0002_issue_body_massege_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Massege",
            new_name="Message",
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Opened"), (2, "In progress"), (3, "Closed")]
            ),
        ),
    ]
