# Generated by Django 4.2.11 on 2024-05-04 13:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_activationkey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationkey",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
